### PR TITLE
Tomas' solutions for #20

### PR DESCRIPTION
**Pull request by TomasEliz**

### CODE REVIEW

**Review by ciamac-da — CHANGES_REQUESTED** [review]
Hey Tomas:) you forgot putting console. before log!

**Comment by TomasEliz** [comment]
Hey Ciamac, sorry, I got to your request just now.
So I created a variable let log = console.log; at the beginning of the
file, which I always use for logging into the console. It's less typing:)
Or do you mean that some output doesn't appear in the terminal?

**Comment by ciamac-da** [comment]
ups:)) Sorry my bad, yeah you right you always store console.log() inside of a variable at the beginning like your other exercises!

**Review by ciamac-da — APPROVED** [review]

**Comment by TomasEliz** [comment]
cool, no worries:)

**Pull request merged**
